full_column_headings = [

    # General Data
    "Game Code",
    "Player Name",
    "Stakes",
    "Small Blind",
    "Big Blind",
    "Max Players",
    "Game Type",
    "Date",
    "Time",

    "Table Name",
    "Chips ($)",
    "Chips (BB)",
    "Player Cards",
    "Position",

    "Flop Card 1",
    "Flop Card 2",
    "Flop Card 3",
    "Turn Card",
    "River Card",

    "Winners",
    "Winning Hands",
    "Winning Rankings",

    # pre-flop
    "Added to Pot Pre-Deal",
    "Check Pre-Flop",
    "Facing Pre-Flop Limp",
    "Pre-Flop Limp",

    "Facing Pre-Flop Raise",
    "Pre-Flop Raise",
    "Pre-Flop Raise Size",
    "Pre-Flop Raise to",
    "Pre-Flop Raise Position",
    "Called Pre-Flop Raise",
    "Called Pre-Flop Raise size",
    "Fold to Pre-Flop Raise",
    "Facing Pre-Flop 3-Bet",

    "Pre-Flop 3-Bet",
    "Pre-Flop 3-Bet Size",
    "Pre-Flop 3-Bet to",
    "Pre-Flop 3-Bet Position",
    "Called Pre-Flop 3-Bet",
    "Called Pre-Flop 3-Bet Size",

    "Fold to Pre-Flop 3-Bet",
    "Facing Pre-Flop 4-Bet",
    "Pre-Flop 4-Bet",
    "Pre-Flop 4-Bet Size",
    "Pre-Flop 4-Bet to",
    "Pre-Flop 4-Bet Position",
    "Called Pre-Flop 4-Bet",
    "Called Pre-Flop 4-Bet Size",
    "Fold to Pre-Flop 4-Bet",

    "Facing Pre-Flop 5-Bet",
    "Pre-Flop 5-Bet",
    "Pre-Flop 5-Bet Size",
    "Pre-Flop 5-Bet to",
    "Pre-Flop 5-Bet Position",
    "Called Pre-Flop 5-Bet",
    "Called Pre-Flop 5-Bet Size",
    "Fold to Pre-Flop 5-Bet",

    "Facing Pre-Flop 6-Bet",
    "Pre-Flop 6-Bet",
    "Pre-Flop 6-Bet Size",
    "Pre-Flop 6-Bet to",
    "Pre-Flop 6-Bet Position",
    "Called Pre-Flop 6-Bet",
    "Called Pre-Flop 6-Bet Size",
    "Fold to Pre-Flop 6-Bet",

    "Pre-Flop Final Pot ($)",
    "Pre-Flop Final Pot (BB)",
    "Pre-Flop Added to Pot",

    # Flop
    "Check Flop",

    "Facing Flop Raise",
    "Flop Raise",
    "Flop Raise Size",
    "Flop Raise to",
    "Flop Raise Position",
    "Called Flop Raise",
    "Called Flop Raise size",
    "Fold to Flop Raise",

    "Flop Re-raise",
    "Flop Re-raise Size",
    "Flop Re-raise to",
    "Flop Re-Raise Position",
    "Facing Flop Re-Raise",
    "Called Flop Re-raise",
    "Called Flop Re-raise Size",
    "Fold to Flop Re-raise",

    "Facing Flop 3-Bet",
    "Flop 3-Bet",
    "Flop 3-Bet Size",
    "Flop 3-Bet to",
    "Flop 3-Bet Position",
    "Called Flop 3-Bet",
    "Called Flop 3-Bet Size",
    "Fold to Flop 3-Bet",

    "Facing Flop 4-Bet",
    "Flop 4-Bet",
    "Flop 4-Bet Size",
    "Flop 4-Bet to",
    "Flop 4-Bet Position",
    "Called Flop 4-Bet",
    "Called Flop 4-Bet Size",
    "Fold to Flop 4-Bet",

    "Facing Flop 5-Bet",
    "Flop 5-Bet",
    "Flop 5-Bet Size",
    "Flop 5-Bet to",
    "Flop 5-Bet Position",
    "Called Flop 5-Bet",
    "Called Flop 5-Bet Size",
    "Fold to Flop 5-Bet",

    "Facing Flop 6-Bet",
    "Flop 6-Bet",
    "Flop 6-Bet Size",
    "Flop 6-Bet to",
    "Flop 6-Bet Position",
    "Called Flop 6-Bet",
    "Called Flop 6-Bet Size",
    "Fold to Flop 6-Bet",

    "Flop Final Pot ($)",
    "Flop Final Pot (BB)",
    "Flop Added to Pot",

    # Turn
    "Check Turn",

    "Facing Turn Raise",
    "Turn Raise",
    "Turn Raise Size",
    "Turn Raise to",
    "Turn Raise Position",
    "Called Turn Raise",
    "Called Turn Raise size",
    "Fold to Turn Raise",
    "Facing Turn Re-Raise",

    "Turn Re-raise",
    "Turn Re-raise Size",
    "Turn Re-raise to",
    "Turn Re-raise Position",
    "Called Turn Re-raise",
    "Called Turn Re-raise Size",
    "Fold to Turn Re-raise",

    "Facing Turn 3-Bet",
    "Turn 3-Bet",
    "Turn 3-Bet Size",
    "Turn 3-Bet to",
    "Turn 3-Bet Position",
    "Called Turn 3-Bet",
    "Called Turn 3-Bet Size",
    "Fold to Turn 3-Bet",

    "Facing Turn 4-Bet",
    "Turn 4-Bet",
    "Turn 4-Bet Size",
    "Turn 4-Bet to",
    "Turn 4-Bet Position",
    "Called Turn 4-Bet",
    "Called Turn 4-Bet Size",
    "Fold to Turn 4-Bet",

    "Facing Turn 5-Bet",
    "Turn 5-Bet",
    "Turn 5-Bet Size",
    "Turn 5-Bet to",
    "Turn 5-Bet Position",
    "Called Turn 5-Bet",
    "Called Turn 5-Bet Size",
    "Fold to Turn 5-Bet",

    "Facing Turn 6-Bet",
    "Turn 6-Bet",
    "Turn 6-Bet Size",
    "Turn 6-Bet to",
    "Turn 6-Bet Position",
    "Called Turn 6-Bet",
    "Called Turn 6-Bet Size",
    "Fold to Turn 6-Bet",

    "Turn Final Pot ($)",
    "Turn Final Pot (BB)",
    "Turn Added to Pot",

    # River
    "Check River",
    "Facing River Raise",
    "River Raise",
    "River Raise Size",
    "River Raise to",
    "River Raise Position",
    "Called River Raise",
    "Called River Raise size",
    "Fold to River Raise",

    "Facing River Re-Raise",
    "River Re-raise",
    "River Re-raise Size",
    "River Re-raise to",
    "River Re-Raise Position",
    "Called River Re-raise",
    "Called River Re-raise Size",
    "Fold to River Re-raise",

    "Facing River 3-Bet",
    "River 3-Bet",
    "River 3-Bet Size",
    "River 3-Bet to",
    "River 3-Bet Position",
    "Called River 3-Bet",
    "Called River 3-Bet Size",
    "Fold to River 3-Bet",

    "Facing River 4-Bet",
    "River 4-Bet",
    "River 4-Bet Size",
    "River 4-Bet to",
    "River 4-Bet Position",
    "Called River 4-Bet",
    "Called River 4-Bet Size",
    "Fold to River 4-Bet",

    "Facing River 5-Bet",
    "River 5-Bet",
    "River 5-Bet Size",
    "River 5-Bet to",
    "River 5-Bet Position",
    "Called River 5-Bet",
    "Called River 5-Bet Size",
    "Fold to River 5-Bet",

    "Facing River 6-Bet",
    "River 6-Bet",
    "River 6-Bet Size",
    "River 6-Bet to",
    "River 6-Bet Position",
    "Called River 6-Bet",
    "Called River 6-Bet Size",
    "Fold to River 6-Bet",

    "River Final Pot ($)",
    "River Final Pot (BB)",
    "River Added to Pot",

    # All In
    "All In",
    "All In Street",
    "All In Action",
    "Facing All In Raise",
    "Call All In Raise",
    "Fold to All In Raise",
    "Raise Over All In Raise",

    "Total Added to Pot",

    # Hand Rankings
    "Pocket Pair",
    "Suited Hand",
    "Has Straight",

    # "Pot Increase Pre-Flop",
    # "Pot Increase Flop",
    # "Pot Increase Turn",
    # "Pot Increase River",
]
