full_column_headings = [
    # General Data
    "Player Name",
    "Stakes",
    "Max Players",
    "Game Type",
    "Date",
    "Time",
    "Game Code",
    "Table Name",
    "Chips ($)",
    "Chips (BB)",
    "Player Cards",
    "Position",
    "Flop Card 1",
    "Flop Card 2",
    "Flop Card 3",
    "Turn Card",
    "River Card",
    "Winners",
    "Winning Hands",
    "Winning Rankings",
    # pre-flop
    "Check Pre-Flop",
    "Pre-Flop Limp",
    "Pre-Flop Raise",
    "Pre-Flop Raise Size",
    "Pre-Flop Raise to",
    "Called Pre-Flop Raise",
    "Called Pre-Flop Raise size",
    "Fold to Pre-Flop Raise",
    "Pre-Flop 3-Bet",
    "Pre-Flop 3-Bet Size",
    "Pre-Flop 3-Bet to",
    "Called Pre-Flop 3-Bet",
    "Called Pre-Flop 3-Bet Size",
    "Fold to Pre-Flop 3-Bet",
    "Pre-Flop 4-Bet",
    "Pre-Flop 4-Bet Size",
    "Pre-Flop 4-Bet to",
    "Called Pre-Flop 4-Bet",
    "Called Pre-Flop 4-Bet Size",
    "Fold to Pre-Flop 4-Bet",
    "Pre-Flop 5-Bet",
    "Pre-Flop 5-Bet Size",
    "Pre-Flop 5-Bet to",
    "Called Pre-Flop 5-Bet",
    "Called Pre-Flop 5-Bet Size",
    "Fold to Pre-Flop 5-Bet",
    "Pre-Flop 6-Bet",
    "Pre-Flop 6-Bet Size",
    "Pre-Flop 6-Bet to",
    "Called Pre-Flop 6-Bet",
    "Called Pre-Flop 6-Bet Size",
    "Fold to Pre-Flop 6-Bet",
    # flop
    "Check Flop",
    "Flop Raise",
    "Flop Raise Size",
    "Flop Raise to",
    "Called Flop Raise",
    "Called Flop Raise size",
    "Fold to Flop Raise",
    "Flop Re-raise",
    "Flop Re-raise Size",
    "Flop Re-raise to",
    "Called Flop Re-raise",
    "Called Flop Re-raise Size",
    "Fold to Flop Re-raise",
    "Flop 3-Bet",
    "Flop 3-Bet Size",
    "Flop 3-Bet to",
    "Called Flop 3-Bet",
    "Called Flop 3-Bet Size",
    "Fold to Flop 3-Bet",
    "Flop 4-Bet",
    "Flop 4-Bet Size",
    "Flop 4-Bet to",
    "Called Flop 4-Bet",
    "Called Flop 4-Bet Size",
    "Fold to Flop 4-Bet",
    "Flop 5-Bet",
    "Flop 5-Bet Size",
    "Flop 5-Bet to",
    "Called Flop 5-Bet",
    "Called Flop 5-Bet Size",
    "Fold to Flop 5-Bet",
    "Flop 6-Bet",
    "Flop 6-Bet Size",
    "Flop 6-Bet to",
    "Called Flop 6-Bet",
    "Called Flop 6-Bet Size",
    "Fold to Flop 6-Bet",
    # Turn
    "Check Turn",
    "Turn Raise",
    "Turn Raise Size",
    "Turn Raise to",
    "Called Turn Raise",
    "Called Turn Raise size",
    "Fold to Turn Raise",
    "Turn Re-raise",
    "Turn Re-raise Size",
    "Turn Re-raise to",
    "Called Turn Re-raise",
    "Called Turn Re-raise Size",
    "Fold to Turn Re-raise",
    "Turn 3-Bet",
    "Turn 3-Bet Size",
    "Turn 3-Bet to",
    "Called Turn 3-Bet",
    "Called Turn 3-Bet Size",
    "Fold to Turn 3-Bet",
    "Turn 4-Bet",
    "Turn 4-Bet Size",
    "Turn 4-Bet to",
    "Called Turn 4-Bet",
    "Called Turn 4-Bet Size",
    "Fold to Turn 4-Bet",
    "Turn 5-Bet",
    "Turn 5-Bet Size",
    "Turn 5-Bet to",
    "Called Turn 5-Bet",
    "Called Turn 5-Bet Size",
    "Fold to Turn 5-Bet",
    "Turn 6-Bet",
    "Turn 6-Bet Size",
    "Turn 6-Bet to",
    "Called Turn 6-Bet",
    "Called Turn 6-Bet Size",
    "Fold to Turn 6-Bet",
    # River
    "Check River",
    "River Raise",
    "River Raise Size",
    "River Raise to",
    "Called River Raise",
    "Called River Raise size",
    "Fold to River Raise",
    "River Re-raise",
    "River Re-raise Size",
    "River Re-raise to",
    "Called River Re-raise",
    "Called River Re-raise Size",
    "Fold to River Re-raise",
    "River 3-Bet",
    "River 3-Bet Size",
    "River 3-Bet to",
    "Called River 3-Bet",
    "Called River 3-Bet Size",
    "Fold to River 3-Bet",
    "River 4-Bet",
    "River 4-Bet Size",
    "River 4-Bet to",
    "Called River 4-Bet",
    "Called River 4-Bet Size",
    "Fold to River 4-Bet",
    "River 5-Bet",
    "River 5-Bet Size",
    "River 5-Bet to",
    "Called River 5-Bet",
    "Called River 5-Bet Size",
    "Fold to River 5-Bet",
    "River 6-Bet",
    "River 6-Bet Size",
    "River 6-Bet to",
    "Called River 6-Bet",
    "Called River 6-Bet Size",
    "Fold to River 6-Bet",
]
